### ISSUE TITLE
can it add to nvim-lsp-installer client

### ISSUE THREAD

**Issue by tinywaferShark** [imc-trading/svlangserver#17]
I want to use [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) instead of coc.nvim. How to add it to this LSP client?

**Comment by kkanhere** [comment]
Have you checked https://github.com/williamboman/nvim-lsp-installer/blob/main/CUSTOM_SERVERS.md ? I don't use nvim so don't know the exact configuration.
Thanks
