### ISSUE TITLE
Can not go to the definition

### ISSUE THREAD

**Issue by otutay** [imc-trading/svlangserver#20]
Hi All,
Go to definition is not working to find the typedef declerations in an package file. Although it is working a few days ago. I have checked the index.json file and all of the declared signals are crawled there. I have already try to reinstall the package. What should i do?

**Comment by kkanhere** [comment]
Can you please provide an example? Because seems to be working fine for me for some sample code I tried.
Thanks

**Comment by otutay** [comment]
Hi Again,
I have updated the visual studio and problem is solved. Thanks for your time.
